---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/doctors":
    get:
      summary: List all doctors
      tags:
      - Doctors
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
    post:
      summary: Create a doctor
      tags:
      - Doctors
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                image:
                  type: string
                specialization:
                  type: string
                consultation_fee:
                  type: number
                hospital:
                  type: string
                availability:
                  type: boolean
                facebook:
                  type: string
                instagram:
                  type: string
                twitter:
                  type: string
              required:
              - name
              - description
              - specialization
  "/api/v1/doctors/{id}":
    parameters:
    - name: id
      in: path
      description: ID of a doctor
      required: true
      schema:
        type: string
    - name: Authorization
      in: header
      schema:
        type: string
    get:
      summary: Show a doctor's details
      tags:
      - Doctors
      responses:
        '200':
          description: Successful
        '404':
          description: Not found
        '401':
          description: Unauthorized
    delete:
      summary: Delete a doctor
      tags:
      - Doctors
      responses:
        '204':
          description: No content
        '404':
          description: Not found
        '401':
          description: Unauthorized
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
