default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: microverse
  password: 123456789

development:
  <<: *default
  database: lanzz-project-development

test:
  <<: *default
  database: lanzz-project-test

production:
  <<: *default
  database: lanzz-project-production
