default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: Davidrama

development:
  <<: *default
  database: fullstack-project-development

test:
  <<: *default
  database: fullstack-project-test

production:
  <<: *default
  database: fullstack-project-production
