default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: microverse-final-capstone-development

test:
  <<: *default
  database: microverse-final-capstone-test

production:
  <<: *default
  database: microverse-final-capstone-production
